import React from 'react';
import { Link } from 'react-router-dom';
import { Search, FileText, Zap } from 'lucide-react';

export default function Home() {
  return (
    <div className="hero-section animate-in">
      <h1 className="hero-title">
        Accelerate Your <br/>
        <span style={{ background: 'linear-gradient(135deg, var(--brand-primary), var(--brand-secondary))', WebkitBackgroundClip: 'text', WebkitTextFillColor: 'transparent' }}>
          Learning Journey
        </span>
      </h1>
      <p className="hero-subtitle animate-in delay-100">
        Harness the power of AI to instantly generate comprehensive notes, find the best tutorial videos, and summarize lengthy study documents.
      </p>
      
      <div style={{ display: 'flex', gap: '1rem', justifyContent: 'center' }} className="animate-in delay-200">
        <Link to="/search" className="btn-primary">
          <Search size={20} />
          Explore a Topic
        </Link>
        <Link to="/summarizer" className="btn-secondary">
          <FileText size={20} />
          Summarize Document
        </Link>
      </div>

      <div className="cards-grid animate-in delay-300" style={{ marginTop: '5rem' }}>
        <Link to="/search" className="glass-card" style={{ display: 'block', textDecoration: 'none' }}>
          <Zap size={32} style={{ color: 'var(--brand-primary)', marginBottom: '1rem' }} />
          <h3>Instant Notes</h3>
          <p style={{ color: 'var(--text-muted)', marginTop: '0.5rem' }}>
            Type any valid topic and instantly receive well-structured, easy-to-understand notes generated by advanced AI.
          </p>
        </Link>
        <Link to="/search" className="glass-card" style={{ display: 'block', textDecoration: 'none' }}>
          <div style={{ display: 'flex', gap: '0.5rem', marginBottom: '1rem' }}>
            <div style={{ width: '32px', height: '32px', background: '#ff0000', borderRadius: '8px', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
              <svg fill="white" viewBox="0 0 24 24" width="16" height="16"><path d="M8 5v14l11-7z"/></svg>
            </div>
          </div>
          <h3>Curated Videos</h3>
          <p style={{ color: 'var(--text-muted)', marginTop: '0.5rem' }}>
            Get recommendations for the best YouTube tutorials and explanations corresponding to your topic.
          </p>
        </Link>
        <Link to="/summarizer" className="glass-card" style={{ display: 'block', textDecoration: 'none' }}>
           <FileText size={32} style={{ color: 'var(--brand-secondary)', marginBottom: '1rem' }} />
           <h3>Smart Summaries</h3>
           <p style={{ color: 'var(--text-muted)', marginTop: '0.5rem' }}>
            Upload PDFs or text documents to extract the key takeaways and main ideas in seconds.
           </p>
        </Link>
      </div>
    </div>
  );
}
